### ISSUE TITLE
Updated, now it can't send messages.

### ISSUE THREAD

**Issue by Raggitator** [TaureHorn/FoundryVTT_ChatConsole#54]
So I updated this mod yesterday and now I can't send any messages through it.
Here's what the error log says:
"foundry.js:6667 TypeError: Cannot read properties of undefined (reading 'active')
    at ConsoleApp._updateObject (consoleApp.js:543:85)
    at ConsoleApp._onSubmit (foundry.js:6664:18)"

Is there a hotfix for this?

I can use the console commands, f.e. /alias and /incognito just fine. Tried turning off the timestamps, but it didn't help.

**Comment by TaureHorn** [comment]
I'm guessing that you do not have the Simple Calendar module installed at all. Correct?

If you could confirm for me that the data for your consoles includes the key `timestamps: <true or false>`, that'd be really helpful too. If you're unsure how to do that, you can left click on of the icons in the header of a console to copy the id to your clipboard. Then open your browser console and type `ConsoleData.getConsole("")` and paste the id between the " " quote marks and hit enter.

**Comment by TaureHorn** [comment]
I wasn't able to recreate the exact error message you posted but I got something similar. I'm pretty confident that I fixed the issue you are having in 1e483cfd4a8862f79752f7fee578265ef749badc. Update in foundry and it should work fine. 

I'm gonna mark this issue as closed. But on the off chance your issue is still something I haven't caught please let me know in this thread, thanks.
